# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta', models.FileField(upload_to='')),
                ('number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('img', models.ImageField(upload_to='')),
                ('chromosome_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chromosome_specie_X', to='comparisonManager.Chromosome')),
                ('chromosome_y', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chromosome_specie_Y', to='comparisonManager.Chromosome')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('short_name', models.CharField(max_length=10)),
                ('accesion_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='chromosome',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparisonManager.Specie'),
        ),
    ]
