# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_x1', models.BigIntegerField()),
                ('gen_x2', models.BigIntegerField()),
                ('product', models.CharField(default='No data found.', max_length=200)),
                ('note', models.CharField(default='No data found.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta', models.URLField(max_length=250)),
                ('number', models.CharField(max_length=2)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('img', models.ImageField(max_length=500, upload_to='')),
                ('csv', models.CharField(max_length=500)),
                ('chromosome_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chromosome_specie_X', to='comparisonManager.Chromosome')),
                ('chromosome_y', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chromosome_specie_Y', to='comparisonManager.Chromosome')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('short_name', models.CharField(max_length=10)),
                ('accesion_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='chromosome',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparisonManager.Specie'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparisonManager.Specie'),
        ),
    ]
