# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-30 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisonManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='note',
            field=models.CharField(default='No data found.', max_length=500),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='product',
            field=models.CharField(default='No data found.', max_length=500),
        ),
    ]
