# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisonManager', '0002_auto_20170929_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromosome',
            name='fasta',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='chromosome',
            name='number',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='img',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='specie',
            name='accesion_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
