# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-31 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisonManager', '0002_auto_20190530_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='strand',
            field=models.IntegerField(default=1),
        ),
    ]
